[package]
name = "openbanking_escrow"
type = "contract"
authors = ["Mach 34"]

[dependencies]
authwit = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.75.0", directory="noir-projects/aztec-nr/authwit"}
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.75.0", directory="noir-projects/aztec-nr/aztec" }
openbanking_verifier = { path = "../../lib" }
token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.75.0", directory="noir-projects/noir-contracts/contracts/token_contract" }